apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-app-myntra
  template:
    metadata:
      labels:
        app: ingress-app-myntra
    spec:
      #imagePullSecrets:
      # - name: k8spoonam.azurecr.io
      containers:
      - name: myntra-app
        image: ${IMAGE_NAME}:${BUILD_NUMBER}
        ports:
        - containerPort: 80


